### ISSUE TITLE
#if(variable) fails check if variable exists in context

### ISSUE THREAD

**Issue by deze333** [vapor/leaf-kit#31]
Quoting Leaf documentation about `#if`:

> if you provide a variable it will check that variable exists in its context

The latest Leaf engine doesn't follow this convention: it only evaluates Bool `true` as true, all other values including `nil` and strings evaluated as `false`.

In other words, no matter what you provide it'll always be treated as `false` unless Bool `true` provided.

Small experiment:

```html
<p>Title = #(title)<br>
#if(title):
    The 'title' is #(title)
#else:
    No 'title' was provided.
#endif
</p>

<p>Nonexistent = #(nonexistent)<br>
#if(nonexistent):
    The 'nonexistent' is #(nonexistent)
#else:
    No 'nonexistent' was provided.
#endif
</p>
```

Results in:

```
Title = Home
No 'title' was provided.

Nonexistent =
No 'nonexistent' was provided.
```

**Comment by b-straub** [comment]
You may have a look to my long standing pull request that might have been overlooked:
 [Fix for conditional logic](https://github.com/vapor/leaf-kit/pull/28)

**Comment by deze333** [comment]
Trying to bring the contributors' awareness to this bug on Discourse. It's a pretty annoying problem actually. Hoping more people will stumble upon it.
