### ISSUE TITLE
Error including partials at top level via #extend

### ISSUE THREAD

**Issue by deze333** [vapor/leaf-kit#33]
Getting an "unresolved ast" error when trying to `#extend` an HTML snippet into the top-level template.

But have no problems using `#extend` of the same snippet at lower levels.

The `#embed` tag seems to have been deprecated... yet it was so handy for inclusions of simple snippets.

Is there a workaround for this? 

**` base.leaf`**

```html
<!doctype html>
<html lang="en">
<head>
</head>
<body>
    ✅This works here:
    #extend("partials/picture.svg"):#endextend

    #import("body")
</body>
</html>
```

**`page.leaf`**

```html
#extend("base"):
    #export("title", "Some website")
    #export("description", "Some page")

    #export("body"):

        🛑 This doesn't work here: [ ERROR ] unresolved ast
        #extend("partials/picture.svg"):#endextend

    #endexport
#endextend
```

**`picture.svg`**

```html
<svg>
    <path d="M0...">
</svg>
```

**Comment by tanner0101** [comment]
cc @loganwright
