### ISSUE TITLE
Leaf removes non-keywords that follow `#`

### ISSUE THREAD

**Issue by deze333** [vapor/leaf-kit#40]
Perhaps somewhat related to #16 ... Parser removes all words that begin with `#` even if no matching Leaf keyword exists.

This leads to subtle bugs, for example Bootstrap mobile menus stop working. Such a problem isn't immediately obvious and as a first time "gotcha" takes quite some time to figure out why and implement escaping. Too easy to miss.

Leaf silently transforms `data-target="#navbarCollapse"` into `data-target=""`

This markup breaks:

```html
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
```

Escaped version obviously works:

```html
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="\#navbarCollapse">
```

**Comment by tdotclare** [comment]
Closed in LeafKit-1.0.0tau
