### ISSUE TITLE
Suggestion: increased granular control over template caching

### ISSUE THREAD

**Issue by tdotclare** [vapor/leaf-kit#42]
Allowing some control over LeafCache beyond `isEnabled` would be great for certain use cases where templates themselves are dynamically controlled in use (in my case I want to be able to generate additional, user defined templates live in production, for example with email templates), but as it stands there's no way to clear cached, resolved documents while the app is running.

My naive solution is just to add a purge function to LeafCache protocol - in the current implementation, this is pretty basic but gets 95% of what's necessary done.

```swift
@discardableResult func purge(
        _ name: String,
        on loop: EventLoop
    ) -> EventLoopFuture<Bool?>
```

It returns an optional Bool meaning:

- **nil** - no cached document existed for the path
- **true** - cached document was purged
- **false** - not currently returned but would in future mean that a document is cached for that path, but could not be purged because other templates have dependencies on it

Since extended templates resolve inline when they're processed, this does mean that cached templates dependent on purged documents would still continue to use the previously loaded template unless they themselves are purged, which.... is of dubious desirability, but any more complex behavior would require maintaining a dependency graph alongside, and I realize that may be outside the scope of what you'd like LeafKit to handle.

[Fork Comparison Detail](https://github.com/vapor/leaf-kit/compare/master...tdotclare:cache-control)

**Comment by deze333** [comment]
Cache purging is something I was going to ask about as well. Without that I have to regularly restart the app container on each smallest template update. A simple purge function that forces Leaf to reload all templates would be a mega awesome help!

**Comment by tdotclare** [comment]
Happy to do a PR for the addition I've made, with the caveat that it may be confusing to some people that cached templates won't automatically update and would need to be purged themselves in order to update.

An ideally robust version of this would require cache entries to have a dependency graph indicating which other templates reference it, and a purging/reload method would have an option to control how purge/reloads handle dependencies (think like SQL insert/update restrict/cascade logic)

**Comment by deze333** [comment]
Yes, a PR would be great! Personally, I am very happy to just have an ability to implement a manual reload from admin. 

Potentially, creating a file watcher and dynamically reload the whole template tree on change could be the next step. But even simple manual purge/reload functionality is better than none.

**Comment by tdotclare** [comment]
@tanner0101 PR ok for this?

**Comment by tanner0101** [comment]
+1 to a PR for this
