### ISSUE TITLE
index not working inside for loop

### ISSUE THREAD

**Issue by bottlehall** [vapor/leaf-kit#45]
I'm using Leaf 4.0.0-rc1.2 and Leaf-Kit 1.0.0-rc1.2. I've tried a minimal route to test index in a for loop but get an error:

/Users/npr/Dropbox/Apps/rv4/Resources/Views/for.leaf: unable to match TagDeclaration(name: "", parameters: Optional([variable(name)]), expectsBody: true) with TagDeclaration(name: "endfor", parameters: nil, expectsBody: false)

The .leaf file is:
```swift
#for(name in names):
#(name):#(index)
#endfor
```
If I take the reference to index out, then it works as expected.

**Comment by tdotclare** [comment]
Current LeafKit is missing a fair number of tags from previous versions of Leaf, including internal loop references, unfortunately. Hope to get them back in soon.
