### ISSUE TITLE
`#extend` should be able to take an expression

### ISSUE THREAD

**Issue by microtherion** [vapor/leaf-kit#54]
Constructing names on the fly can be quite useful, e.g.:

```
#for(cloud in clouds):
   #extend("cloud/" + #(cloud) + "_logo")
   #extend("cloud/" + #(cloud) + "_button")
#endfor
```

**Comment by tdotclare** [comment]
On my roadmap for further down the line after release.

**Comment by 0xTim** [comment]
This is out of scope for Leaf, but may be supported in Tau so I recommend you check that out!
