### ISSUE TITLE
Nested-scope (e.g. conditional) imports in files extended from loop are not resolved

### ISSUE THREAD

**Issue by ffried** [vapor/leaf-kit#57]
As requested in #56, this is the issue tracking the bug, that imports aren't resolved when they happen in certain nested scopes inside the imported file.

The two test cases I've written in #56 are here:

```swift
func testLoopedConditionalImport() throws {
    var test = TestFiles()
    test.files["/base.leaf"] = """
    #for(x in list):
    #extend("entry"):#export("something", "Whatever")#endextend
    #endfor
    """
    test.files["/entry.leaf"] = """
    #(x): #if(isFirst):#import("something")#else:Not First#endif
    """

    let expected = """

    A: Whatever

    B: Not First

    C: Not First

    """

    let renderer = LeafRenderer(
        configuration: .init(rootDirectory: "/"),
        cache: DefaultLeafCache(),
        files: test,
        eventLoop: EmbeddedEventLoop()
    )

    let page = try renderer.render(path: "base", context: ["list": ["A", "B", "C"]]).wait()
    XCTAssertEqual(page.string, expected)
}

func testMultipleLoopedConditionalImports() throws {
    var test = TestFiles()
    test.files["/base.leaf"] = """
    #for(x in list1):
    #extend("entry"):#export("something", "Whatever")#endextend
    #endfor
    #for(x in list2):
    #extend("entry"):#export("something", "Something Else")#endextend
    #endfor
    """
    test.files["/entry.leaf"] = """
    #(x): #if(isFirst):#import("something")#else:Not First#endif
    """

    let expected = """

    A: Whatever

    B: Not First

    C: Not First


    A: Something Else

    B: Not First

    C: Not First

    """

    let renderer = LeafRenderer(
        configuration: .init(rootDirectory: "/"),
        cache: DefaultLeafCache(),
        files: test,
        eventLoop: EmbeddedEventLoop()
    )

    let page = try renderer.render(path: "base", context: [
        "list1": ["A", "B", "C"],
        "list2": ["A", "B", "C"],
    ]).wait()
    XCTAssertEqual(page.string, expected)
}
```

Furthermore, `imports` might appear in all kinds of different places (e.g. inside parameters of another tag).
One thing I noticed in my approach to it, is that care has to be taken with `Conditional` since it's a class. My first approach was not resolving imports in repetitive `extend`s correctly anymore, because the `Conditional` in the included file was only created once and thus only resolved in the first pass. The second `embed` would show the `export`s of the first `extend`. This is covered by the second test-case, though.

**Comment by tdotclare** [comment]
Thanks for the push!

#58 fixes this issue
 * adds support for expressions, variables and other parameter types as the value for 2-parameter #export format
* adds support for import() being called inside parameters
* converts Conditional to a struct rather than a class
* and improves performance by maintaining reference state on Syntaxes to prevent brute-force resolution of ASTs

**Comment by ffried** [comment]
@tdotclare Thanks for taking this on so quickly! 👍
