### ISSUE TITLE
utf8 support

### ISSUE THREAD

**Issue by tanner0101** [vapor/leaf-kit#6]
Currently Leaf parses templates using `ByteBuffer` (byte-by-byte). We should consider moving to `String` for UTF-8 support. Especially now that String is natively UTF-8 in Swift 5.

**Comment by calebkleveter** [comment]
While `String` uses UTF-8 internally, operations are still very slow compared to arrays. I'm not sure about `ByteBuffer`. As an example, I am working on a markdown parser. I was lexing a String, and it took ~23 seconds to do a 28kb file. When I simply changed to `[UInt8]`, it took ~0.018 seconds. Maybe I was doing something wrong, but I thought I'd bring it up 😄

**Comment by tanner0101** [comment]
@calebkleveter I'm not sure we have a choice though. If I understand correctly, it's possible that ASCII symbols can appear anywhere inside of multi-byte characters. For example, if you're parsing a markdown file and inside of a multi-byte emoji there is the byte 0x60 (backtick), then your byte-based parser would think it needs to parse a code snippet. If you were using an abstraction like `String`, and parsing `Character`s, then this would not be an issue as all of the bytes for that emoji would be contained in a single character. 

This isn't a problem for HTTP since the protocol requires that headers be ASCII (basically). For example, it's invalid to do something like this in HTTP:

```http
GET / HTTP/1.1
X-Foo: 🤠
```

If those multi-byte characters had any of the HTTP-specific identifiers in them, like `:`, `\r`, `\n`, etc, it would totally break parsing. However, the HTTP-body can contain whatever encoding you like (even outside of UTF8). That's because you know the length of the body (or you're using a transfer-encoding), so you don't need to look at any of the body bytes. So you can do:

```http
GET / HTTP/1.1
Content-Length: 4

🤠
```

PS: I got `4` from this snippet:

```swift
print("🤠".utf8.count) // 4
```

For things like Markdown / Leaf however, we don't have the same luxury as HTTP. Both formats can be nested in arbitrary UTF-8 encoded data. So I think to make a valid parser, you must account for that.

**Comment by tanner0101** [comment]
@calebkleveter you are right (ignore my previous response). We should use `ByteBuffer`.

**Comment by MrMage** [comment]
@calebkleveter which APIs on `String` have you been using? Especially on Swift 5, maybe there's a faster middle ground providing the safety of `String`, but with better performance?

**Comment by calebkleveter** [comment]
@MrMarge I was iterating over characters, so I was mostly just using the `index` methods.

**Comment by MrMage** [comment]
> @MrMarge I was iterating over characters, so I was mostly just using the `index` methods.

I think the runtime of the index operations can be linear in the value of the index. So if you access all N characters in of a String via their index, you might end up with N^2 runtime. Did you try looping over `string` or `string.unicodeScalars` instead, or used `string.map` or `string.reduce`? Do you maybe have a short example of what you tried so I could take a look?

I am a bit worried that looping over individual bytes could indeed have unintended side effects on non-ASCII strings; maybe we could get a `String`-based implementation "fast enough" to not be problematic. Most templates are only going to be parsed once for the server's runtime, after all.

**Comment by calebkleveter** [comment]
@MrMage The commits will be a bit out of order, but I think you should be able to use https://github.com/calebkleveter/SwiftMark/pull/6/commits/8761dbc384e6c06f40014804e8481204faf5505e for `String` lexing and https://github.com/calebkleveter/SwiftMark/pull/6/commits/134e049b14e7a465d46834662a6bc0b05a030617 for `[UInt8]` lexing.

**Comment by grundoon** [comment]
I _think_ (as @MrMage alludes to) that quadratic runtime has inadvertently been introduced with https://github.com/calebkleveter/SwiftMark/blob/8761dbc384e6c06f40014804e8481204faf5505e/Sources/Utilities/CollectionTracker.swift#L5-L7 – since `distance(from:to:)` is O(n) itself.

Perhaps `for (index, character) in zip(string.indices, string) { ... }` (or even just `in string.enumerated()`, though that'd be equivalent `Int`s rather than true `Index`s) would provide a single canonical iteration more appropriate to the task?

**Comment by calebkleveter** [comment]
@grundoon `distance(from:to:)` is `O(1)` for `RandomeAccessCollection`, so `[UInt8]` falls under that. However, `String` does not, so it is complexity `O(k)` where `k` is the resulting distance.

**Comment by MrMage** [comment]
> @grundoon `distance(from:to:)` is `O(1)` for `RandomeAccessCollection`, so `[UInt8]` falls under that. However, `String` does not, so it is complexity `O(k)` where `k` is the resulting distance: https://developer.apple.com/documentation/swift/collection/3017672-distance

@calebkleveter another option: I think `Array(string)` should create an `[Character]` array. That should give us the benefits of correct UTF-8 handling combined with decent performance; did you try that? (Haven't tested it myself.)

**Comment by calebkleveter** [comment]
@MrMage Just benchmarked `[Character]`. While it was still significantly faster than `String`, it was 10-15% slower than a byte array (`[UInt8]`).

I did test this in release mode by the way.

**Comment by MrMage** [comment]
> @MrMage Just benchmarked `[Character]`. While it was still significantly faster than `String`, it was 10-15% slower than a byte array (`[UInt8]`).
> 
> I did test this in release mode by the way.

Given that parsing happens only once, a 10% speed difference shouldn't have an impact. I'd go with `[Character]` then, to not have to worry about any UTF-8 gotchas at all.

**Comment by tdotclare** [comment]
@tanner0101 can we close this as not being relevant to current state of LeafKit since we're pretty much built on Character at this point?

**Comment by tanner0101** [comment]
Yeah I'm fine with that. Ideally we'd move to [UInt8] eventually, so maybe leave it open as a long standing feature request? But either why I don't mind.
