### ISSUE TITLE
CustomTag does not work within #embed/#set/#get

### ISSUE THREAD

**Issue by cweinberger** [vapor/leaf-kit#76]
When embedding content using `#get/set` that contains a custom tag which uses a `Client` to fetch information, the content is not displayed / empty.

I have added a couple of examples to visualize the issue:

* http://localhost:8080/leaf/example1 - works as expected, uses [`SimpleTag`](https://github.com/cweinberger/LeafClientIssue/blob/master/Sources/App/LeafTags/SimpleTag.swift)
* http://localhost:8080/leaf/example2 - does not work, body is empty, uses [`ClientTag`](https://github.com/cweinberger/LeafClientIssue/blob/master/Sources/App/LeafTags/ClientTag.swift).
* http://localhost:8080/leaf/example3 - does not work, same as example2, but it shows, that we can render the [`ClientTag`](https://github.com/cweinberger/LeafClientIssue/blob/master/Sources/App/LeafTags/ClientTag.swift) outside of body.

Example repo: https://github.com/cweinberger/LeafClientIssue
Examples deployed on vapor.cloud:
* https://leafissue-development.vapor.cloud/leaf/example1
* https://leafissue-development.vapor.cloud/leaf/example2
* https://leafissue-development.vapor.cloud/leaf/example3

**Comment by 0xTim** [comment]
@cweinberger is this still an issue?

**Comment by cweinberger** [comment]
Didn't test it with Leaf 4. I'd assume since it's a rewrite, probably not

**Comment by 0xTim** [comment]
Ok, I'll close this then. Feel free to reopen if it you need!
