### ISSUE TITLE
Reversing Tau reintroduced issue compiling on Arm64

### ISSUE THREAD

**Issue by tomcomer** [vapor/leaf-kit#80]
The issue is in `LeafKit/LeafData/LeafDataRepresentable.swift`. The offending line is 
```swift
extension Float80: LeafDataRepresentable {}
```
Which needs to be changed to 
```swift
#if arch(i386) || arch(x86_64)
extension Float80: LeafDataRepresentable {}
#endif
```
in order to compile on a raspberry pi.

**Comment by 0xTim** [comment]
Thanks, I've fixed this for the final release
