### ISSUE TITLE
Xcode Warnings on Xcode 13.3

### ISSUE THREAD

**Issue by Sherlouk** [vapor/leaf-kit#99]
### Describe the bug

> 'self' refers to the method 'LeafKeyword.self', which may be unexpected

```
SourcePackages/checkouts/leaf-kit/Sources/LeafKit/LeafLexer/LeafParameterTypes.swift:67:44: warning: 'self' refers to the method 'LeafKeyword.self', which may be unexpected
    internal var identity: Bool { self == .`self` }
                                           ^
SourcePackages/checkouts/leaf-kit/Sources/LeafKit/LeafLexer/LeafParameterTypes.swift:67:44: note: use 'LeafKeyword.self' to silence this warning
    internal var identity: Bool { self == .`self` }
                                           ^
                                           LeafKeyword.
<unknown>:0: warning: 'self' refers to the method 'LeafKeyword.self', which may be unexpected
<unknown>:0: note: use 'LeafKeyword.self' to silence this warning
```

### To Reproduce

Build a Vapor project with `leaf-kit` in it on Xcode 13.3

### Expected behavior

No Xcode warnings should exist

### Environment

vapor: stable 18.3.3

FYI: the issue template says to use `vapor --version` but this command doesn't exist any longer.

**Comment by 0xTim** [comment]
As a first instance we should check with the latest nightly toolchain to see if this is a compiler bug that's been fixed or not

**Comment by 0xTim** [comment]
I think this is a compiler bug - raised as https://bugs.swift.org/browse/SR-15897
